// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.API.Data;

namespace SmartSchool.API.Migrations
{
    [DbContext(typeof(SmartContext))]
    partial class SmartContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("SmartSchool.API.Model.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Luiza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Model.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoID", "DisciplinaID");

                    b.HasIndex("DisciplinaID");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoID = 1,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 1,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 1,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoID = 2,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 2,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 2,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoID = 3,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 3,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 3,
                            DisciplinaID = 3
                        },
                        new
                        {
                            AlunoID = 4,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 4,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 4,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoID = 5,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 5,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoID = 6,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 6,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 6,
                            DisciplinaID = 3
                        },
                        new
                        {
                            AlunoID = 6,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 3
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Model.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorID");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Matemática",
                            ProfessorID = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Física",
                            ProfessorID = 2
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Português",
                            ProfessorID = 3
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Inglês",
                            ProfessorID = 4
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Programação",
                            ProfessorID = 5
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Model.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Lauro"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Roberto"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ronaldo"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Alexandre"
                        });
                });

            modelBuilder.Entity("SmartSchool.API.Model.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool.API.Model.Aluno", "Aluno")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("AlunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool.API.Model.Disciplina", "Disciplina")
                        .WithMany("AlunosDisciplinas")
                        .HasForeignKey("DisciplinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.API.Model.Disciplina", b =>
                {
                    b.HasOne("SmartSchool.API.Model.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
